/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as OQueFazemosRouteImport } from './routes/o-que-fazemos'
import { Route as IndiceGovernancaIaRouteImport } from './routes/indice-governanca-ia'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosRoute = OQueFazemosRouteImport.update({
  id: '/o-que-fazemos',
  path: '/o-que-fazemos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceGovernancaIaRoute = IndiceGovernancaIaRouteImport.update({
  id: '/indice-governanca-ia',
  path: '/indice-governanca-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/indice-governanca-ia': typeof IndiceGovernancaIaRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/indice-governanca-ia': typeof IndiceGovernancaIaRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRoute
  '/indice-governanca-ia': typeof IndiceGovernancaIaRoute
  '/o-que-fazemos': typeof OQueFazemosRoute
  '/publicacoes': typeof PublicacoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/eventos'
    | '/indice-governanca-ia'
    | '/o-que-fazemos'
    | '/publicacoes'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/eventos'
    | '/indice-governanca-ia'
    | '/o-que-fazemos'
    | '/publicacoes'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/eventos'
    | '/indice-governanca-ia'
    | '/o-que-fazemos'
    | '/publicacoes'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EventosRoute: typeof EventosRoute
  IndiceGovernancaIaRoute: typeof IndiceGovernancaIaRoute
  OQueFazemosRoute: typeof OQueFazemosRoute
  PublicacoesRoute: typeof PublicacoesRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos': {
      id: '/o-que-fazemos'
      path: '/o-que-fazemos'
      fullPath: '/o-que-fazemos'
      preLoaderRoute: typeof OQueFazemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice-governanca-ia': {
      id: '/indice-governanca-ia'
      path: '/indice-governanca-ia'
      fullPath: '/indice-governanca-ia'
      preLoaderRoute: typeof IndiceGovernancaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EventosRoute: EventosRoute,
  IndiceGovernancaIaRoute: IndiceGovernancaIaRoute,
  OQueFazemosRoute: OQueFazemosRoute,
  PublicacoesRoute: PublicacoesRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
