/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as InstitutoRouteImport } from './routes/instituto'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as IndexRouteImport } from './routes/index'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutoRoute = InstitutoRouteImport.update({
  id: '/instituto',
  path: '/instituto',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forum': typeof ForumRoute
  '/framework': typeof FrameworkRoute
  '/instituto': typeof InstitutoRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forum': typeof ForumRoute
  '/framework': typeof FrameworkRoute
  '/instituto': typeof InstitutoRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forum': typeof ForumRoute
  '/framework': typeof FrameworkRoute
  '/instituto': typeof InstitutoRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/solucoes': typeof SolucoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forum'
    | '/framework'
    | '/instituto'
    | '/knowledge-hub'
    | '/solucoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forum'
    | '/framework'
    | '/instituto'
    | '/knowledge-hub'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/forum'
    | '/framework'
    | '/instituto'
    | '/knowledge-hub'
    | '/solucoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForumRoute: typeof ForumRoute
  FrameworkRoute: typeof FrameworkRoute
  InstitutoRoute: typeof InstitutoRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituto': {
      id: '/instituto'
      path: '/instituto'
      fullPath: '/instituto'
      preLoaderRoute: typeof InstitutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForumRoute: ForumRoute,
  FrameworkRoute: FrameworkRoute,
  InstitutoRoute: InstitutoRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
